/**
 * Post-build PWA step (run by `bun run build` after `vite build`):
 *
 *   1. Copy dist/client/_shell.html → dist/client/index.html.
 *      TanStack Start's SPA mode emits the prerendered client shell as
 *      `_shell.html`. Cloudflare's static-asset SPA fallback
 *      (`not_found_handling: "single-page-application"`), like most static
 *      hosts, serves `/index.html` for unmatched navigations like
 *      /mix/<uuid>. Without the copy, deep links 404.
 *
 *   2. Generate dist/client/sw.js, a dependency-free service worker that
 *      precaches every built asset (hashed chunks incl. the mp3 decoder
 *      worker, css, icons, magic.dat, the shell) so the app boots fully
 *      offline. Cache name = content hash of the file list, so every deploy
 *      activates a fresh cache and deletes the old one.
 *
 * Hand-rolled instead of vite-plugin-pwa: the plugin's workbox step doesn't
 * run under TanStack Start's multi-environment vite build (it emits only
 * its registration stub, never the worker). ~60 lines we own beats a
 * silently-broken black box.
 */

import { createHash } from 'node:crypto'
import {
  copyFileSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { join, relative } from 'node:path'

const CLIENT_DIR = join(import.meta.dir, '..', 'dist', 'client')

// 1. Shell copy ─────────────────────────────────────────────────────────────
copyFileSync(join(CLIENT_DIR, '_shell.html'), join(CLIENT_DIR, 'index.html'))

// 2. Collect precache list ──────────────────────────────────────────────────
function walk(dir: string): string[] {
  const out: string[] = []
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    if (statSync(full).isDirectory()) out.push(...walk(full))
    else out.push(full)
  }
  return out
}

const EXCLUDE = new Set(['sw.js', '_shell.html'])
const files = walk(CLIENT_DIR).filter((f) => {
  const rel = relative(CLIENT_DIR, f).replaceAll('\\', '/')
  if (EXCLUDE.has(rel)) return false
  if (rel.endsWith('.map')) return false // source maps: big, useless offline
  return true
})

const hash = createHash('sha256')
const urls: string[] = []
let totalBytes = 0
for (const f of files.sort()) {
  const rel = relative(CLIENT_DIR, f).replaceAll('\\', '/')
  // Cloudflare Workers Assets 307-redirects /index.html to /, and the Cache
  // API rejects redirected responses. Precaching /index.html would fail the
  // whole cache.addAll and break the service worker install, and with it PWA
  // install and offline support. Precache the canonical / instead.
  urls.push(rel === 'index.html' ? '/' : `/${rel}`)
  const bytes = readFileSync(f)
  totalBytes += bytes.byteLength
  hash.update(rel)
  hash.update(bytes)
}
const version = hash.digest('hex').slice(0, 12)

// 3. Emit the worker ────────────────────────────────────────────────────────
const sw = `/* Generated by scripts/build-sw.ts. Do not edit. */
const CACHE = 'kosatka-${version}'
const PRECACHE = ${JSON.stringify(urls)}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const req = event.request
  if (req.method !== 'GET') return
  const url = new URL(req.url)
  if (url.origin !== self.location.origin) return
  // Navigations: network-first so new deploys are picked up while online,
  // falling back to the cached shell offline (client router handles the path).
  if (req.mode === 'navigate') {
    event.respondWith(fetch(req).catch(() => caches.match('/')))
    return
  }
  // Assets: cache-first, hashed filenames make them immutable.
  event.respondWith(
    caches.match(req).then((hit) => hit ?? fetch(req)),
  )
})
`
writeFileSync(join(CLIENT_DIR, 'sw.js'), sw)

console.log(
  `[build-sw] index.html copied, sw.js generated, cache kosatka-${version}, ` +
    `${urls.length} precached files, ${(totalBytes / 1024 / 1024).toFixed(2)} MiB`,
)
