/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RpfRpfIdRouteImport } from './routes/rpf/$rpfId'
import { Route as MixSessionIdRouteImport } from './routes/mix/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RpfRpfIdRoute = RpfRpfIdRouteImport.update({
  id: '/rpf/$rpfId',
  path: '/rpf/$rpfId',
  getParentRoute: () => rootRouteImport,
} as any)
const MixSessionIdRoute = MixSessionIdRouteImport.update({
  id: '/mix/$sessionId',
  path: '/mix/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mix/$sessionId': typeof MixSessionIdRoute
  '/rpf/$rpfId': typeof RpfRpfIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mix/$sessionId': typeof MixSessionIdRoute
  '/rpf/$rpfId': typeof RpfRpfIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mix/$sessionId': typeof MixSessionIdRoute
  '/rpf/$rpfId': typeof RpfRpfIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mix/$sessionId' | '/rpf/$rpfId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mix/$sessionId' | '/rpf/$rpfId'
  id: '__root__' | '/' | '/mix/$sessionId' | '/rpf/$rpfId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MixSessionIdRoute: typeof MixSessionIdRoute
  RpfRpfIdRoute: typeof RpfRpfIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpf/$rpfId': {
      id: '/rpf/$rpfId'
      path: '/rpf/$rpfId'
      fullPath: '/rpf/$rpfId'
      preLoaderRoute: typeof RpfRpfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mix/$sessionId': {
      id: '/mix/$sessionId'
      path: '/mix/$sessionId'
      fullPath: '/mix/$sessionId'
      preLoaderRoute: typeof MixSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MixSessionIdRoute: MixSessionIdRoute,
  RpfRpfIdRoute: RpfRpfIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
